### ISSUE TITLE
Math symbols missing from documentation

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#150] opened 2019-03-18 13:09 UTC
For example, https://tskit.readthedocs.io/en/latest/python-api.html#tskit.LdCalculator.r2_array has the nonsensical phrase " If the returned array is and direction is tskit.FORWARD then is the value of the statistic for and , the value for and , etc."

The python documentation uses e.g. 

```
:math:`a` and :math:`a - 2`
```

here, but there's obviously some error in converting this into the online docs

**Comment by jeromekelleher** [comment] 2019-03-18 17:02
Must be something missing from the sphinx setup.

**Comment by jeromekelleher** [comment] 2019-03-27 15:29
I've just looked at this and it's rendering fine for me. What browser are you on?

**Comment by hyanwong** [comment] 2019-03-27 17:09
It seems to be working fine for me now. Must have been a network or browser error. Sorry

**Comment by hyanwong** [comment] 2019-09-29 10:32
This seems to have popped up again, e.g. on https://msprime.readthedocs.io/en/stable/api.html - I have checked in several browsers

![Screenshot 2019-09-29 at 11 32 11](https://user-images.githubusercontent.com/4699014/65831026-d22e1b00-e2ac-11e9-8c0d-078b1baef7bf.png)

**Comment by petrelharp** [comment] 2019-09-30 02:23
Hmph; I see that also. For some reason mathjax is not getting included (grep the source for "mathjax"), even though it is when I build locally, and the mathjax extension is included in sphinx's conf.py. It might have to do with a transition to mathjax 3.0, I suppose.

**Comment by jeromekelleher** [comment] 2019-09-30 07:56
Anyone fancy digging in to this to see what the issue is?

**Comment by hyanwong** [comment] 2019-09-30 08:12
Sorry - deep in ProbGen poster design. Happy to in a week or so.

**Comment by petrelharp** [comment] 2019-10-02 02:01
Same - later, but not now.

**Comment by hyanwong** [comment] 2019-11-22 11:37
Magically this seems to have resolved itself. I guess the issue can be closed @jeromekelleher ?

**Comment by jeromekelleher** [comment] 2019-11-26 16:58
I'm not sure this is a problem: the ``latest`` version on RTD is rendering the maths fine: https://msprime.readthedocs.io/en/latest/api.html, and the stable and latest versions on RTD of tskit both seem to renders maths fine as well.

So, it'll probably sort itself out whenever the next version of msprime is released?

**Comment by jeromekelleher** [comment] 2019-12-10 08:16
Closing --- this is rendering fine now.

**Closed by jeromekelleher** 2019-12-10 08:16 UTC
Labels: bug
