### ISSUE TITLE
More details output when conversion to tree_sequence fails?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1012] opened 2020-11-18 21:33 UTC
When we fail to convert a table collection to a tree sequence, we get error messages like:

```
A mutation's time must be < the parent node of the edge on which it occurs, or be marked as 'unknown'
```

If more information about the location of the error in the tables is known, it would be really helpful to output this too. I guess sometimes this isn't possible, but for those cases where it is, it would really help track down problems.

**Comment by jeromekelleher** [comment] 2020-11-18 23:40
Can't be done because errors are propagated back from C via integers, which don't allow for any context to be provided. You're welcome to help improving the [error messages](https://github.com/tskit-dev/tskit/blob/main/c/tskit/core.c#L121), though.

I'm going to close this as unresolvable.

**Closed** 2020-11-18 23:40 UTC

**Comment by jeromekelleher** [comment] 2020-11-18 23:42
We could provide debug logging in the C library, but it would quite tricky and a lot of work to do well.

**Comment by benjeffery** [comment] 2020-11-19 00:26
It could get messy - but we could keep the first two bytes of the error code for the type and use the rest for data such as row number that caused the error (you'd have to deal with the case where the row is was to big to fit). I guess a global integer set by error cases can't be used for threading reasons?

**Comment by jeromekelleher** [comment] 2020-11-19 00:40
It's a good idea encoding some info in the spare bytes, but it would be a lot of work and it hardly seems worth it tbh. Even returning non-static strings is a major headache.

Keeping a global state is an absolute last resort for concurrency reasons, as you say.

**Comment by petrelharp** [comment] 2020-11-19 01:05
To debug that one, @hyanwong, you could build the tree sequence without the mutations, then do `ts.at( )` to get the relevant tree, and see where the problem is?

**Comment by hyanwong** [comment] 2020-11-19 09:21
It's not usually that particular message that is raised when I encounter problems. I did think this was not something easy to do, but @benjeffery thought it might be possible/easy in some cases. If not, it's probably too much work to sort out any time soon, so I guess we should just leave this closed. It is a perennial niggle, though.

**Comment by benjeffery** [comment] 2020-11-19 09:50
I'd like to keep the list of open issues as things we are definitely going to do in the medium-term, so best to keep this closed - It might be an idea to have a list of ideas for future work that are not planned. As issues like this come in that are good ideas, but that we don't plan to do soon we close them and add them to the list. Thinking about it a label might do. Maybe "icebox" or "future"? This would keep our list of open issues smaller and manageable, but still allow open discussion on "future" issues.

**Comment by jeromekelleher** [comment] 2020-11-19 10:07
I honestly don't see how we can do this without adding a *lot* of complexity to the C code. It would be a lot easier and more productive I think to write a ``debug`` (or something) function in python which would look at the table collection and tell you what's wrong with it. Sure there's a bit of code duplication, but it's better than spending a month going through the C code and making it less readable and more brittle.
