### ISSUE TITLE
Fixup tests for lshmm 0.0.6

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2962] opened 2024-06-20 09:45 UTC
Recent lshmm release breaks some tests in tskit test suite: https://github.com/astheeggeggs/lshmm/releases/tag/v0.0.6

Would you mind look at this please @szhan

**Comment by jeromekelleher** [comment] 2024-06-20 10:15
Note we'll need to update the pins in ``requirements``

**Comment by szhan** [comment] 2024-06-20 16:55
When doing `pytest -vs test_haplotype_matching.py`, I encountered a bunch of failed tests that hit value error.

```python
ValueError: First value in the recombination probability array must be zero.
```

I think it is caused by a line assigning recombination probabilities in, for example:
```python
def check_viterbi(ts, h, recombination=None, mutation=None):
    h = np.array(h).astype(np.int8)
    m = ts.num_sites
    assert len(h) == m
    if recombination is None:
        recombination = np.zeros(ts.num_sites) + 1e-9 # First value is positive.
```

Similarly, `check_forward_matrix` and `check_backward_matrix`.

**Comment by szhan** [comment] 2024-06-20 16:59
I'm not sure if this is intended, but mutation probability is set to 0 across all sites here.

```python
def check_viterbi(ts, h, recombination=None, mutation=None):
    h = np.array(h).astype(np.int8)
    m = ts.num_sites
    assert len(h) == m
    if recombination is None:
        recombination = np.zeros(ts.num_sites) + 1e-9
    if mutation is None:
        mutation = np.zeros(ts.num_sites)
```

**Comment by szhan** [comment] 2024-06-21 17:34
I've added stricter requirements on the input data, e.g., having all variable sites in the ref. panel and query combined. It is causing some tests to fail, I think.

**Comment by szhan** [comment] 2024-06-21 18:27
I'm encountering these errors when running the tests locally.
* First value in the recomb. prob. array is `0`. This can be fixed by setting the first value to `0`.
* Some invariant sites in the samples.
* `ValueError: More than one root exists. Use tree.roots instead`.

**Comment by szhan** [comment] 2024-06-24 13:48
Note that we are now using lshmm `0.0.8`.

**Closed** 2024-06-24 13:52 UTC
