### ISSUE TITLE
Node labels in to_nexus are ambiguous

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1803] opened 2021-10-17 09:35 UTC
As @jeetsukumaran points out our default node labels in ``to_nexus`` are ambiguous as they are in the form ``"tsk_{node.id}_{node.flags}"``, and these would be interpreted as ``"tsk {node.id} {node.flags}"`` by conformant nexus parsers.

Since it's unlikely many people are using the to_nexus functionality at the moment (given that it's broken! #1785 ) I think we're free to change things around a bit. 

The idea of including the ID and flags in the label is so that samples can be identified, but maybe the flags are extraneous for most applications (the samples are nearly always be the leaf nodes), and we would be better off keeping things simple and just including the ID. The idea of the ``tsk`` prefix is that some things get confused by integer names, but maybe that's extraneous as well. So, perhaps the best default behaviour would be to simply use the bare ID values?

As we're updating the method, I think it's worthwhile adding (or at least planning for) custom node labels as well, via a mapping like we use in the current "newick" method. (Which we're planning on deprecating, #1671 )

Any thoughts here @jeetsukumaran? Great to get your input here so that we can at least lay the foundations for getting good interoperability with the classical phylo formats.

**Comment by jeetsukumaran** [comment] 2021-10-17 23:26
As I noted in the thread discussing #1801, just leaving the underscores in as-is unquoted, will work fine (for most folks, most of the time) even when interoperating with other nexus-compliant programs. The semantics will differ, but it is syntactically correct, and ambiguity/confusion in interpretation of the labels only will arise when mixing outputs from programs with different assumptions (and that output data that uses the internally-normalized labels). These latter cases throw some obvious errors and can be handled.

Another option is just to swap in a valid token that is not subject to any ambiguity and can be emitted/parsed without quoting. I would suggest using a caret ("`^`"; so "`tsk^{node.id}^{node.flags}`"). This seems to be handled by most programs without issue, and is preserved through round-tripping. The period ("`.`") also *mostly* works, but at least as of a few years ago, there were some programs in the wild that, for some strange idiosyncratic reason, stripped periods from labels.

What I ended up doing in dendropy is just provide a very rich interface for client code to decide what their labels are going to look like. Lots of true/false options, and all can be overridden by a client-supplied function object passed to the writer that will take a node as an argument and return the string rendering. 

The other big thing is to whether or not the trees should be seen as rooted vs unrooted. Typically, a tree string is prepended with "`[&R]`" to indicate a rooted tree vs "`[&U]`" an unrooted tree. This is a fairly standard convention and widely -supported. The problem is when such a token is not present, should the trees be considered unrooted (even if there is a basal bifurcation) or rooted? Here there is no consensus. Many and maybe most bioinformatics programs assume rooted trees, but PAUP* (which for me is the reference standard for the Nexus foramt) assumes unrooted trees (and so does DendroPy).

Maybe we can think about how much tskit wants to invest in data parsing/writing. My suggestion is that maybe tskit can emit some basically compliant nexus/newick for now, that works for most folks most of the time. If there is an interest in extending its data writing/parsing capabilities and there is no objection to introducing dendropy as a dependency, then in the longer term, then we can bring in dendropy to do all the heavy-lifting in that regard. All these internals will be hidden to the client code, of course, though we can expose the DendroPy writer/parser API in the "to_nexus()" method signature -- this will allow for very flexible and highly customizable output (and input) in a range of formats.

**Comment by jeetsukumaran** [comment] 2021-10-18 16:45
(1) Given the policy of very limited data ingest, I think it makes sense to similarly target a minimal output, and leave it to 3rd party tools to do the conversion to the full diversity of formats. This minimal output should be capable of expressing all data and metadata unambiguously. For character data, I presume you've got that covered between fasta and vcf. For the phylogenetics community the fasta is sufficient as well.  For tree data, I think newick nexus is fine. Given all that, maybe just focus on getting the fasta/nexus/newick to where you are happy would be a good objective.

With limited parsing/output format as a design principle, this can be done without dendropy as a dependency. (Incidentally, I was not aware that dendropy was even bundled with bioconda! I personally maintain it as standalone, with primary deployment is through pip/github as well as pypi. One of the explicit design goals is no third-party dependencies for ultra-straightforward installation).

(2) Bare integer labels are syntactically correct and *generally* will be interpreted correctly. I would avoid them though -- *if* there is a TRANSLATE block, then there might be some confusion whether we are looking at the numerical index of a taxon or the label of the taxon. (To be clear: the Nexus parser has no ambiguity: it will resolve to the taxon label as a priority if there is a direct match, and only if not fall back to the numerical index interpretation. But *users* might get confused). Fortunately, all this can eaily be avoided by simply prepending a string or character to the number (e.g., "`tsk42`","`t42`", etc.). 

(3) As things stand, the three things that need to be added to the nexus/newick output:

(3.1) some convention for default labeling -- this should be simple to avoid dealing with quotes etc. If there is no need for separators because the label is simply the node id (e.g., "`tsk42`"), then that's fine. Otherwise use "^" (e.g., "`tsk_42_341`"). 
(3.2) some convention for handling quotes in the case of user-supplied labels (https://github.com/tskit-dev/tskit/issues/1812)
(3.3) inclusion of the rooted/unrooted token

For (3.1) -- the default labeling -- it would be really nice if there is complete/unambiguous identity of labels for the same data outputted in fasta, newick, nexus, etc. formats. So, for example, a third-party program can read a fasta file for the mutations can work together with the tree file for the genealogy. (This is a place where the quoted vs unquoted underscores matters, as an underscore in a fasta label will be interpreted as an underscore, quoted or not).  So maybe the labeling should be abstracted out into some library-wide function or variable or configuration that is called whenever a label is needed. And maybe even formally documented as the convention? This way it can not only should be shared across formats, but client code/programs know what to expect and can plan how to handle/manipulate the data, and would be useful as well as in terms of internal expectations for tests.

**Closed** 2021-11-04 12:52 UTC
Labels: bug, Python API
