### ISSUE TITLE
simplify() still doesn't support migrations?

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#1621] opened 2021-08-11 01:18 UTC
A note to myself to investigate, and fix later -- I've heard from a user that simplify() cannot be used on tree sequences with migration records, and this seems to be hard-coded in [here](https://github.com/tskit-dev/tskit/blob/a7413ffe4c302fb08aaa494f854758600e88bc7c/c/tskit/tables.c#L8657).

I imagine this was originally because the nodes in the migration records might be unary and so would be removed by simplify() running with all defaults, but surely it should be okay when `keep_unary=True` now?

**Comment by petrelharp** [comment] 2021-08-11 05:01
It's true! This is #20, and we just haven't gotten around to it - no very good reason for the omission.

**Comment by jeromekelleher** [comment] 2021-08-11 08:22
Shall we close this as it's a dupe of #20?

**Closed** 2021-08-11 09:40 UTC
Labels: enhancement
