### ISSUE TITLE
merging tree sequences from parallel runs

### ISSUE THREAD

**Issue by ShyamieG** [tskit-dev/tskit#2510] opened 2022-09-19 21:51 UTC
I have what might be a pretty unusual case of needing to merge a set of related tree sequences. I am simulating the evolution of a pathogen as infections are transmitted from one individual to another through time. I first simulate the infection network (epidemiological simulation) and then go back and simulate the genomes, using SLiM, as they follow the simulated infection paths (evolutionary genomic simulation). My SLiM scripts simulate pathogen reproduction within an infected individual and output the resulting tree sequence, which becomes input for the next iteration of the SLiM script (i.e. the individual to whom the infection is transmitted to next). One contagious individual can infect more than one susceptible individual, so the tree sequences can diverge and continue in parallel at various points in the infection scenario.

The result of my simulations are a set of tree sequences that have been 'sampled' from a population of infected individuals, and are related to each other by the epidemiological simulation. So far, so good. My goal now is to merge these tree sequences to get a unified tree sequence representing the genetic ancestry of all the sampled pathogens. I have figured out that I must use the union() function, but I'm running into some problems actually executing it.

To illustrate, I've attached [some code and four tree sequences](https://github.com/tskit-dev/tskit/files/9602548/merge_example.zip) that represent the tips of a clade within my infection network. In my example, 1 and 2 diverge first (14 time steps ago) then 3 and 4 diverge (41 time steps ago).

![ex_inf_network](https://user-images.githubusercontent.com/51133211/191117802-d60941ce-259b-4c57-aee5-4097f5b375bd.jpg)

My idea is to iteratively merge sister tips until I am left with just one tree (e.g. 1&2 and 3&4, then 12&34). I match nodes based on the IDs that slim assigns them, renaming nodes that are younger than the divergence of the two infections in question. Even after accounting for possible discrepancies, I find that merging trees fails pretty frequently.

In my example, if I try to merge trees 1 and 2 when 'check_shared_equality = True' union() fails with the error 'Shared portions of the tree sequences are not equal.'. I can set 'check_shared_equality = False' and merge trees 1 and 2 just fine. But do I want to do this? I'm not sure what it means for the shared portions to be equal vs. not. In what cases would it be okay to set this parameter to False?

If I try to merge trees 3 and 4, however, even setting 'check_shared_equality = False' does not work, and union() fails with a different error - 'Bad edges: contradictory children for a given parent over an interval, or indexes need to be rebuilt.'. I have spent a lot of time trying to figure out what constitutes a 'bad edge' and how to fix it, but I am not sure how to go about identifying these problematic edges. For example, trees 1 and 2 have edges where child nodes are discordant in their parents or left/right coordinates, but this does not appear to present a problem (at least not when 'check_shared_equality = False'). The message suggests that rebuilding the indexes might help, but I'm not sure how to do this - or what it even means, to be honest.

Sorry for the long post! Thanks for reading and for any advice on how I might be able fix my problem.

**Comment by ShyamieG** [comment] 2022-09-20 17:58
Hi @jeromekelleher, thanks for the response and suggestion!

Yes, my simulations do include recombination.

I was able to pare all four tree sequences down to many fewer nodes, and reproduced the same errors as before. I couldn't quite get tree 3 below 10 nodes, unfortunately, but it's close. [Here](https://github.com/tskit-dev/tskit/files/9610178/small_ts.zip) are these smaller tree sequences, and below are the node and edge tables. Sorry for formatting =\

### Tree sequence 1
**Node table**
╔══╤═════╤══════════╤══════════╤═════╤════════════════════════════════════════╗
║id│flags│population│individual│time │metadata                                ║
╠══╪═════╪══════════╪══════════╪═════╪════════════════════════════════════════╣
║0 │    1│         1│         0│    3│{'slim_id': 753434444, 'is_null': Fal...║
║1 │    1│         1│         1│    1│{'slim_id': 753464568, 'is_null': Fal...║
║2 │    0│         1│        -1│  483│{'slim_id': 741371706, 'is_null': Fal...║
║3 │    0│         1│        -1│  487│{'slim_id': 741343398, 'is_null': Fal...║
║4 │    0│         2│        -1│  723│{'slim_id': 736451156, 'is_null': Fal...║
║5 │    0│         1│        -1│  724│{'slim_id': 736356604, 'is_null': Fal...║
║6 │    0│         3│        -1│  858│{'slim_id': 731917384, 'is_null': Fal...║
║7 │    0│         3│        -1│  896│{'slim_id': 731638600, 'is_null': Fal...║
║8 │    0│         0│        -1│29341│{'slim_id': 6, 'is_null': False, 'gen...║
║9 │    0│         0│        -1│29341│{'slim_id': 8, 'is_null': False, 'gen...║
╚══╧═════╧══════════╧══════════╧═════╧════════════════════════════════════════╝
**Edge table**
╔══╤════════╤════════╤══════╤═════╤════════╗
║id│left    │right   │parent│child│metadata║
╠══╪════════╪════════╪══════╪═════╪════════╣
║0 │ 2600001│ 3480001│     2│    0│        ║
║1 │10980001│12292988│     2│    0│        ║
║2 │17470001│22620001│     2│    0│        ║
║3 │ 2600001│ 3480001│     2│    1│        ║
║4 │10980001│12292988│     2│    1│        ║
║5 │17470001│22620001│     2│    1│        ║
║6 │  830001│ 1590001│     3│    0│        ║
║7 │ 4850001│ 5880001│     3│    0│        ║
║8 │ 7380001│10980001│     3│    0│        ║
║9 │  830001│ 1590001│     3│    1│        ║
║10│ 4850001│ 5880001│     3│    1│        ║
║11│ 7380001│10980001│     3│    1│        ║
║12│ 3480001│ 4850001│     4│    0│        ║
║13│ 3480001│ 4850001│     4│    1│        ║
║14│       0│  830001│     5│    0│        ║
║15│12292988│12400001│     5│    0│        ║
║16│14470001│17470001│     5│    0│        ║
║17│       0│  830001│     5│    1│        ║
║18│12292988│12400001│     5│    1│        ║
║19│14470001│17470001│     5│    1│        ║
║20│ 1590001│ 2600001│     6│    0│        ║
║21│ 5880001│ 7380001│     6│    0│        ║
║22│ 1590001│ 2600001│     6│    1│        ║
║23│ 5880001│ 7380001│     6│    1│        ║
║24│12400001│14470001│     7│    0│        ║
║25│12400001│14470001│     7│    1│        ║
║26│ 4850001│ 5880001│     8│    3│        ║
║27│ 7380001│10980001│     8│    3│        ║
║28│ 3480001│ 4850001│     8│    4│        ║
║29│       0│  830001│     8│    5│        ║
║30│ 1590001│ 2600001│     8│    6│        ║
║31│ 5880001│ 7380001│     8│    6│        ║
║32│12400001│14470001│     8│    7│        ║
║33│ 2600001│ 3480001│     9│    2│        ║
║34│10980001│12292988│     9│    2│        ║
║35│17470001│22620001│     9│    2│        ║
║36│  830001│ 1590001│     9│    3│        ║
║37│12292988│12400001│     9│    5│        ║
║38│14470001│17470001│     9│    5│        ║
╚══╧════════╧════════╧══════╧═════╧════════╝

### Tree sequence 2
**Node table**
╔══╤═════╤══════════╤══════════╤═════╤════════════════════════════════════════╗
║id│flags│population│individual│time │metadata                                ║
╠══╪═════╪══════════╪══════════╪═════╪════════════════════════════════════════╣
║0 │    1│         0│         0│    5│{'slim_id': 753415422, 'is_null': Fal...║
║1 │    1│         0│         1│    5│{'slim_id': 753409656, 'is_null': Fal...║
║2 │    0│         1│        -1│   33│{'slim_id': 753282828, 'is_null': Fal...║
║3 │    0│         1│        -1│  483│{'slim_id': 741371706, 'is_null': Fal...║
║4 │    0│         2│        -1│  723│{'slim_id': 736451156, 'is_null': Fal...║
║5 │    0│         1│        -1│  724│{'slim_id': 736356604, 'is_null': Fal...║
║6 │    0│         0│        -1│  851│{'slim_id': 731927942, 'is_null': Fal...║
║7 │    0│         3│        -1│  858│{'slim_id': 731917384, 'is_null': Fal...║
║8 │    0│         0│        -1│29341│{'slim_id': 6, 'is_null': False, 'gen...║
║9 │    0│         0│        -1│29341│{'slim_id': 8, 'is_null': False, 'gen...║
╚══╧═════╧══════════╧══════════╧═════╧════════════════════════════════════════╝

**Edge table**
╔══╤════════╤════════╤══════╤═════╤════════╗
║id│left    │right   │parent│child│metadata║
╠══╪════════╪════════╪══════╪═════╪════════╣
║0 │       0│  830001│     2│    0│        ║
║1 │ 7380001│10980001│     2│    0│        ║
║2 │12400001│14470001│     2│    0│        ║
║3 │       0│  830001│     2│    1│        ║
║4 │ 7380001│10980001│     2│    1│        ║
║5 │12400001│14470001│     2│    1│        ║
║6 │ 1590001│ 3480001│     3│    0│        ║
║7 │19500001│22620001│     3│    0│        ║
║8 │ 1590001│ 3480001│     3│    1│        ║
║9 │19500001│22620001│     3│    1│        ║
║10│ 3480001│ 4850001│     4│    0│        ║
║11│ 3480001│ 4850001│     4│    1│        ║
║12│  830001│ 1590001│     5│    0│        ║
║13│10980001│12400001│     5│    0│        ║
║14│14470001│19500001│     5│    0│        ║
║15│  830001│ 1590001│     5│    1│        ║
║16│10980001│12400001│     5│    1│        ║
║17│14470001│19500001│     5│    1│        ║
║18│ 4850001│ 5880001│     6│    0│        ║
║19│ 4850001│ 5880001│     6│    1│        ║
║20│ 5880001│ 7380001│     7│    0│        ║
║21│ 5880001│ 7380001│     7│    1│        ║
║22│       0│  830001│     8│    2│        ║
║23│ 7380001│10980001│     8│    2│        ║
║24│12400001│14470001│     8│    2│        ║
║25│ 1590001│ 2600001│     8│    3│        ║
║26│ 3480001│ 4850001│     8│    4│        ║
║27│ 4850001│ 5880001│     8│    6│        ║
║28│ 5880001│ 7380001│     8│    7│        ║
║29│ 2600001│ 3480001│     9│    3│        ║
║30│19500001│22620001│     9│    3│        ║
║31│  830001│ 1590001│     9│    5│        ║
║32│10980001│12400001│     9│    5│        ║
║33│14470001│19500001│     9│    5│        ║
╚══╧════════╧════════╧══════╧═════╧════════╝

**Merging trees 1 and 2 works as long as check_shared_equality = False.**

### Tree sequence 3
**Node table**
╔══╤═════╤══════════╤══════════╤═════╤════════════════════════════════════════╗
║id│flags│population│individual│time │metadata                                ║
╠══╪═════╪══════════╪══════════╪═════╪════════════════════════════════════════╣
║0 │    1│         0│        -1│   38│{'slim_id': 752528956, 'is_null': Fal...║
║1 │    1│         0│        -1│   38│{'slim_id': 752528958, 'is_null': Fal...║
║2 │    0│         1│        -1│   85│{'slim_id': 752228938, 'is_null': Fal...║
║3 │    0│         3│        -1│  473│{'slim_id': 741424314, 'is_null': Fal...║
║4 │    0│         3│        -1│  475│{'slim_id': 741417974, 'is_null': Fal...║
║5 │    0│         1│        -1│  483│{'slim_id': 741371706, 'is_null': Fal...║
║6 │    0│         2│        -1│  723│{'slim_id': 736451156, 'is_null': Fal...║
║7 │    0│         1│        -1│  724│{'slim_id': 736356604, 'is_null': Fal...║
║8 │    0│         3│        -1│  858│{'slim_id': 731917384, 'is_null': Fal...║
║9 │    0│         3│        -1│  896│{'slim_id': 731638600, 'is_null': Fal...║
║10│    0│         0│        -1│29341│{'slim_id': 6, 'is_null': False, 'gen...║
║11│    0│         0│        -1│29341│{'slim_id': 8, 'is_null': False, 'gen...║
╚══╧═════╧══════════╧══════════╧═════╧════════════════════════════════════════╝

**Edge table**
╔══╤════════╤════════╤══════╤═════╤════════╗
║id│left    │right   │parent│child│metadata║
╠══╪════════╪════════╪══════╪═════╪════════╣
║0 │  830001│ 1590001│     2│    0│        ║
║1 │ 3480001│ 5880001│     2│    0│        ║
║2 │ 9060001│10980001│     2│    0│        ║
║3 │17470001│19500001│     2│    0│        ║
║4 │  830001│ 1590001│     2│    1│        ║
║5 │ 3480001│ 5880001│     2│    1│        ║
║6 │ 9060001│10980001│     2│    1│        ║
║7 │17470001│19500001│     2│    1│        ║
║8 │19500001│22620001│     3│    0│        ║
║9 │19500001│22620001│     3│    1│        ║
║10│ 2135916│ 3480001│     4│    0│        ║
║11│12400001│12631165│     4│    0│        ║
║12│14470001│17470001│     4│    0│        ║
║13│ 2135916│ 3480001│     4│    1│        ║
║14│12400001│12631165│     4│    1│        ║
║15│14470001│17470001│     4│    1│        ║
║16│12292988│12400001│     5│    0│        ║
║17│12292988│12400001│     5│    1│        ║
║18│ 7380001│ 9060001│     6│    0│        ║
║19│ 7380001│ 9060001│     6│    1│        ║
║20│       0│  830001│     7│    0│        ║
║21│10980001│12292988│     7│    0│        ║
║22│       0│  830001│     7│    1│        ║
║23│10980001│12292988│     7│    1│        ║
║24│ 1590001│ 2135916│     8│    0│        ║
║25│ 5880001│ 7380001│     8│    0│        ║
║26│ 1590001│ 2135916│     8│    1│        ║
║27│ 5880001│ 7380001│     8│    1│        ║
║28│12631165│14470001│     9│    0│        ║
║29│12631165│14470001│     9│    1│        ║
║30│ 3480001│ 5880001│    10│    2│        ║
║31│ 9060001│10980001│    10│    2│        ║
║32│ 2135916│ 2600001│    10│    4│        ║
║33│12400001│12631165│    10│    4│        ║
║34│ 7380001│ 9060001│    10│    6│        ║
║35│       0│  830001│    10│    7│        ║
║36│ 1590001│ 2135916│    10│    8│        ║
║37│ 5880001│ 7380001│    10│    8│        ║
║38│12631165│14470001│    10│    9│        ║
║39│  830001│ 1590001│    11│    2│        ║
║40│17470001│19500001│    11│    2│        ║
║41│19500001│22620001│    11│    3│        ║
║42│ 2600001│ 3480001│    11│    4│        ║
║43│14470001│17470001│    11│    4│        ║
║44│12292988│12400001│    11│    5│        ║
║45│10980001│12292988│    11│    7│        ║
╚══╧════════╧════════╧══════╧═════╧════════╝

### Tree sequence 4
**Node table**
╔══╤═════╤══════════╤══════════╤═════╤════════════════════════════════════════╗
║id│flags│population│individual│time │metadata                                ║
╠══╪═════╪══════════╪══════════╪═════╪════════════════════════════════════════╣
║0 │    1│         0│        -1│   25│{'slim_id': 752528962, 'is_null': Fal...║
║1 │    1│         1│        -1│   85│{'slim_id': 752228938, 'is_null': Fal...║
║2 │    0│         2│        -1│  290│{'slim_id': 745825540, 'is_null': Fal...║
║3 │    0│         1│        -1│  724│{'slim_id': 736356604, 'is_null': Fal...║
║4 │    0│         0│        -1│29341│{'slim_id': 6, 'is_null': False, 'gen...║
║5 │    0│         0│        -1│29341│{'slim_id': 8, 'is_null': False, 'gen...║
╚══╧═════╧══════════╧══════════╧═════╧════════════════════════════════════════╝

**Edge table**
╔══╤════════╤════════╤══════╤═════╤════════╗
║id│left    │right   │parent│child│metadata║
╠══╪════════╪════════╪══════╪═════╪════════╣
║0 │       0│  830001│     1│    0│        ║
║1 │ 1590001│ 4850001│     1│    0│        ║
║2 │ 5880001│14470001│     1│    0│        ║
║3 │17470001│22620001│     1│    0│        ║
║4 │  830001│ 1590001│     2│    0│        ║
║5 │  830001│ 1590001│     2│    1│        ║
║6 │14470001│17470001│     3│    0│        ║
║7 │14470001│17470001│     3│    1│        ║
║8 │ 4850001│ 5880001│     4│    0│        ║
║9 │       0│  830001│     4│    1│        ║
║10│ 1590001│ 2600001│     4│    1│        ║
║11│ 3480001│ 4850001│     4│    1│        ║
║12│ 5880001│10980001│     4│    1│        ║
║13│12400001│14470001│     4│    1│        ║
║14│ 2600001│ 3480001│     5│    1│        ║
║15│10980001│12400001│     5│    1│        ║
║16│17470001│22620001│     5│    1│        ║
║17│  830001│ 1590001│     5│    2│        ║
║18│14470001│17470001│     5│    3│        ║
╚══╧════════╧════════╧══════╧═════╧════════╝

**Merging trees 3 and 4 does not work even when I set check_shared_equality = False.**

**Comment by jeromekelleher** [comment] 2022-09-20 20:25
> Sorry for formatting =\

(I just edited your comment there to add triple-ticks around the tables. Works OK for most browers when displaying stuff designed for fixed-width output)

**Comment by jeromekelleher** [comment] 2022-09-20 20:27
Great, thanks @ShyamieG! Now, would you mind also pasting in the ``print(ts.draw_text())`` output for these too? They should be small enough to render here.

**Comment by jeromekelleher** [comment] 2022-09-21 07:33
Great, thanks. OK, so I think you want to merge ts3 and ts4 first - if you look at just the first tree in these (which happen to both cover 0-830001), what would the merged tree look like?

**Comment by ShyamieG** [comment] 2022-09-21 14:20
I still get the same errors merging the smaller versions of ts3 and ts4 :(

This is exactly what I did:

```
matches = np.array([tskit.NULL, 2, tskit.NULL, 7, 10, 11])
t3_small.union(t4_small, matches) ## gives "_tskit.LibraryError: Shared portions of the tree sequences are not equal. (TSK_ERR_UNION_DIFF_HISTORIES)"
t3_small.union(t4_small, matches, check_shared_equality=False) ## gives _tskit.LibraryError: Bad edges: contradictory children for a given parent over an interval, or indexes need to be rebuilt. (TSK_ERR_BAD_EDGES_CONTRADICTORY_CHILDREN)
```

**Comment by ShyamieG** [comment] 2022-09-21 15:19
Ah, got it. I think it should look like this:

```
29341.00┊   5   ┊
        ┊   ┃   ┊
896.00  ┊   ┃   ┊
        ┊   ┃   ┊
858.00  ┊   ┃   ┊
        ┊   ┃   ┊
724.00  ┊   4   ┊
        ┊   ┃   ┊
723.00  ┊   ┃   ┊
        ┊   ┃   ┊
483.00  ┊   ┃   ┊
        ┊   ┃   ┊
475.00  ┊   ┃   ┊
        ┊   ┃   ┊
473.00  ┊   ┃   ┊
        ┊   ┃   ┊
85.00   ┊   3   ┊
        ┊ ┃ ┃ ┃ ┊
38.00   ┊ 0 1 2 ┊
        0  830001
```
(0, 1, and 2 descend from 3 - I couldn't find the right symbol for that)

**Comment by jeromekelleher** [comment] 2022-09-22 08:43
Hmm, I don't see quite how to do this, and I don't think this is what ``union`` does. I think you'd need to code up something bespoke I think @ShyamieG - sorry I can't be more help.

**Comment by ShyamieG** [comment] 2022-09-22 18:00
Sorry, I made a mistake drawing the above tree! Thank you for suggesting this, as it is helping me see the potential issues. Labeling nodes by their SLiM ids also helps me avoid confusing myself. These are the starting trees and the expected merged tree for that first interval:

![int1_trees](https://user-images.githubusercontent.com/51133211/191817301-ddc61a9b-e989-4df3-9c65-2dc4fb450ea4.jpg)

There must be a node X relating both '736356604' and '752228938' back to '6', but it seems it has been simplified out of both tree 3 and 4 at some point. This is okay.

By moving along the genome one interval at a time, I was able to narrow down the source of my error to a single interval. Here is that:

![int2_trees](https://user-images.githubusercontent.com/51133211/191817327-d92ead83-9030-4299-b28b-a4de9d09643e.jpg)

I can't really see why merging just these trees would be problematic, but I did notice something weird here. The relationship between 752228938 and 752528962 changes between intervals - in the first, they are parent-child, and in the second they are sisters (both children of 745825540). How could this have happened?

**Comment by petrelharp** [comment] 2022-09-25 05:39
Ah ha - I think you're right here, the problem is that simplification has removed bits of the "shared" portions, so that these shared portions are no longer identical. In this most recent example: you're right that Tree 3 and Tree 4 are clearly mergable, but figuring out how to actually merge them is a serious algorithmic problem. When `union` gets Tree 3 on section 830001-1590001, it's told that "okay 752228938 is a chlid of 8" but then in tree 4 it's told that "752228938 is a child of 745826640"; these things are different, and it can't deal. Of course, we can see that these are not in conflict, but `union` can't, since the overlapping stuff (i.e., all relationships between shared nodes) have to be *identical*.

So, the question seems to be "how to get SLiM to retain this shared stuff without modifying it?"  This is achieved in [this vignette](https://tskit.dev/pyslim/docs/stable/vignette_parallel_phylo.html) by just making sure to do `treeSeqRememberIndividuals( )` on everyone alive right before each tree sequence is saved out; that ensures that anything above that point isn't simplified any further. I'm guessing you haven't done this step?

**Comment by petrelharp** [comment] 2022-09-26 16:24
I'm impressed you figured out how to do this *without* the vignette!

> Regarding tree 4 in my last post - is it okay that the relationship between '752228938' and '752528962' has changed from parent-child to sisters across the two intervals?

Well, it's possible, and the underlying code is very thoroughly checked, so I'd be very surprised if there were a bug like this.  Let's see - suppose that `a` inherits `[0, 10]` from `x` and `[10, 20]` from `y`; now suppose that `x` inherits from `b` and both `b` and `y` inherit from `z`; then on the left interval `a` and `b` are parent-child, and on the right inteval they are sister. I think this works?

**Comment by ShyamieG** [comment] 2022-09-26 16:46
Ahh, yes - I can see that. Thanks for clearing that up!

**Comment by petrelharp** [comment] 2022-09-28 22:08
Great! I'm going to close this but feel free to re-open if this isn't resolved.

**Closed by petrelharp** 2022-09-28 22:08 UTC
