### ISSUE TITLE
variants() method for the Tree class?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1094] opened 2020-12-19 13:27 UTC
I'm trying to co-iterate over genotypes and trees. This would be easy if there was a `Tree.variants()` iterator, like there is a `Tree.sites()` iterator. Then I could go:

```
for tree in ts.trees():
    for v in tree.variants():
        # do stuff with v.genotypes
```

As it is, I guess I could hack it with something like

```
v_iter = ts.variants()
for tree in ts.trees():
    for _ in tree.sites():
        v = next(v_iter)
        # do stuff with v.genotypes
```

but it would be nice not to do this, as it's not an obvious route for others in the same situation. Would adding a `Tree.variants()` iterator be (a) easy to code up and (b) useful for others?

**Comment by jeromekelleher** [comment] 2021-01-04 07:51
This is a dupe of #605 - it's not easy to well though, so probably best to use something like you have above for your own code for now.

**Closed by jeromekelleher** 2021-01-04 07:51 UTC
