### ISSUE TITLE
Reinstate temporarily disabled tests.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#1583] opened 2021-07-21 14:30 UTC
See https://github.com/tskit-dev/tskit/pull/1571

**Comment by jeromekelleher** [comment] 2021-07-21 16:42
These are the BIG_TABLE tests on circleCI

**Comment by jeromekelleher** [comment] 2021-09-02 05:24
Dupe of #1650

**Closed by jeromekelleher** 2021-09-02 05:24 UTC
